[Default]
# This special host holds the default attributions for all the hosts in this files.
ip = "127.0.0.1"
auth_type = "password"
conn_type = "ssh"
fs_mounter = "sshfs"

["北京/server1"]
username = "tefx"
password = "88580323"

["北京/server2"]
username = "tefx"
password = "88580323"

["镇江/MySQL/生产"]
username = "tefx"
password = "88580323"

["镇江/MySQL/测试"]
username = "tefx"
password = "88580323"

["镇江/Backup"]
username = "tefx"
password = "88580323"

["镇江"]
username = "tefx"
password = "88580323"

["江苏/南京/江宁"]
username = "tefx"
password = "88580323"

["江苏/南京"]
username = "tefx"
password = "88580323"

["Galaxy/Solar/Earth"]
username = "tefx"
password = "88580323"

["Galaxy/Solar/Mars"]
username = "tefx"
password = "88580323"